DROP TABLE IF EXISTS antiddos ; CREATE TABLE antiddos ( id int(11) NOT NULL, ip varchar(64) CHARACTER SET utf8 NOT NULL, time varchar(64) CHARACTER SET utf8 NOT NULL ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE antiddos ADD PRIMARY KEY ( id );

ALTER TABLE antiddos MODIFY id int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1;